### ISSUE TITLE
Conflict(s) with TW Toolkit?

### ISSUE THREAD

**Issue by SharpyTr** [The-West-Scripts/The-West-Essentials#1]
Script is great and all but.. It seems there are some.. conflicts with Toolkit script regarding some FF stuff.

For example;
Can't see Hp/Graphs etc button on FF screen now (very Crucial) , also can't see Total number of Critics per person on Reports anymore

**Comment by SharpyTr** [comment]
Nvm, seems to be fine today.

**Comment by TomRobert** [comment]
Fixed with v1.47.1
