### ISSUE TITLE
Not connecting to the TW-DB site

### ISSUE THREAD

**Issue by DanaeMullendore** [The-West-Scripts/The-West-Essentials#2]
The script does not acknowledge when user is logged on to the TW-DB site.

![image](https://user-images.githubusercontent.com/62973990/78092127-6d8d7d80-7401-11ea-831a-867f11e63cb6.png)

**Comment by SharpyTr** [comment]
I don't have that issue

Maybe something to do with;
https://forum.the-west.net/index.php?threads/tw-db-info-english-support.40603/page-103#post-772630

**Comment by DanaeMullendore** [comment]
That fixed the problem. 

Thank you very very much.
