### ISSUE TITLE
the nowrap used in the ShortPopups feature

### ISSUE THREAD

**Issue by UweOhse** [The-West-Scripts/The-West-Essentials#3]
Hello,

this happens with the ShortPopups enabled:

![tw-nowrap](https://user-images.githubusercontent.com/18497839/106005768-d478d300-60b4-11eb-8691-31fabc1e0930.png)

I think the culprit is the style="white-space:nowrap;" introduced in line 6399:
`
 }).replace('<div class="invPopup_body">', '').replace('inventory_popup"', 'invPopup_body $& style="max-width:385px;"><table><td').replace(/bonus_attr tw_green"/g, '$& style="white-space:nowrap;"').replace('<br><br><div class="item_set_bonus">', end + '</td><td style="padding-left:5px;">');`

Removing the nowrap thing will break the display of items with no long texts in it, but using "display: block; width: 190px;" instead of the white-space:nowrap; seems to work fine for me.

Regards, Uwe

**Comment by TomRobert** [comment]
Hi Uwe

Which browser are you using?
And could you give an example for "removing nowrap breaks the display of items with no long texts in it".

**Comment by UweOhse** [comment]
Hello,

i'm using chromium 86. I remember seeing the same the firefox, but can't that machine right now.

![tw-nowrap2](https://user-images.githubusercontent.com/18497839/106390191-7b2bdf00-63e7-11eb-97c1-5c7c5a228f71.png)

Regards, Uwe
