### ISSUE TITLE
Invalid adress when accessing the wiki

### ISSUE THREAD

**Issue by Ehm-InGames** [The-West-Scripts/The-West-Essentials#4]
While using, from the quest display window, the The-West-Essentials magic button "Show the quest on the wiki", the wiki adresse used is wrongly built, containing an additional text "undefined" between quest suite's and "#"quest's name.

F.ex. https://wiki.the-west.fr/wiki/Panier_de_Pâques**undefined**#La_premi.C3.A8re_couleur
The right address is https://wiki.the-west.fr/wiki/Panier_de_Pâques#La_premi.C3.A8re_couleur

PS : happens on The-West France - don't know about other languages

**Comment by Ehm-InGames** [comment]
Update just arrived - works perfectly - thanks a lot !

**Comment by TomRobert** [comment]
Thank you for reporting it :)
